"""backref adjusted

Revision ID: 0da8dcad3bfe
Revises: 0d9b86d4767f
Create Date: 2024-05-29 12:23:59.322332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da8dcad3bfe'
down_revision: Union[str, None] = '0d9b86d4767f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
