"""backref adjusted more

Revision ID: 3c8c1dee02c0
Revises: 0da8dcad3bfe
Create Date: 2024-05-29 12:30:34.754319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8c1dee02c0'
down_revision: Union[str, None] = '0da8dcad3bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
