"""overlapping prob14

Revision ID: 8c69ed61167a
Revises: a0a0ea4218a2
Create Date: 2024-05-29 20:25:41.321121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c69ed61167a'
down_revision: Union[str, None] = 'a0a0ea4218a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
